### ISSUE TITLE
Issue when start playing video

### ISSUE THREAD

**Issue by hamdipro** [winstonwp/omxplayer-controll#2]
![screenshot from 2016-09-09 19-47-46](https://cloud.githubusercontent.com/assets/6583410/18398827/5821d216-76c6-11e6-8049-e407a8612807.png)
![screenshot from 2016-09-09 19-47-58](https://cloud.githubusercontent.com/assets/6583410/18398828/582555d0-76c6-11e6-849d-4e466d9cd8e6.png)

**Comment by winstonwp** [comment]
Would you please specify which version of node, npm and raspbian you are ussing?
I'm not able to reproduce this error. 

```
node --version
npm --version
cat /etc/os-release
```
