### ISSUE TITLE
Does not work as root

### ISSUE THREAD

**Issue by ellensundh** [winstonwp/omxplayer-controll#3]
Thanks for a great library with many functions I been seeking for. I noticed though that I don't get the events when I run my node project as root. Do you have any advice on how to go about it?

**Comment by winstonwp** [comment]
@ellensundh you're welcome, I've been busy these last couple of days but I'll check into it ASAP. Are you sure you are running the latest version 0.1.9?

**Comment by winstonwp** [comment]
Resolved in version 0.1.9 as of Issue #1
