### ISSUE TITLE
User-Agent

### ISSUE THREAD

**Issue by angelramor** [winstonwp/omxplayer-controll#4]
Hi Winston!!

Well it's not a issue, it's a question for you.

Do you have the possibility to use '--user-agent' in the options? or Do you have planned to add this feature?

(--user-agent 'ua' Send specified User-Agent as part of HTTP requests)

Thanks, cheers!!

**Comment by winstonwp** [comment]
Hi angelramon,
Sorry for the delay. 

You can allways use any other omxplayer option using otherArgs for example:
```
omxp.open('path_to_file', {
    audioOutput: 'both',
    blackBackground: true,
    disableKeys: true,
    disableOnScreenDisplay: true,
    otherArgs: ['--user-agent', 'your user agent']
});
```
I havent tested it especifically for `--user-agent` but, fell free to contact me if it doesn't work.
